# Genetic Algorithm For N-Queen Problem

As we know about Genetic Algorithm, this Algorithm needs has three main part: Select, Breed and mutate.
I will break this principals down.

In [139]:
import numpy as np
import random
import matplotlib.pyplot as plt
import pandas as pd
import time

So first I will make my global variables

In [147]:
population_size = 20
number_of_queens = 6
mutation_chance = 0.1
max_loop = 10000

I will initialize a class for making things easier.

In [135]:
class PogChampQueen():
    def __init__(self, pop_size, q_num, mut_chance):
        self.pop_size = pop_size
        self.q_num = q_num
        self.m_ch = mut_chance
    
    #This function will initialize a random population 
    def InitPop(self):
        np.random.seed(round(time.time()))  
        pop=np.random.random_integers(0, self.q_num - 1, (self.pop_size, self.q_num))
        return pop
    
    #This function will check return fitness value of a set
    #We define fitness as how many threats will be made from a single situation
    def Fitness(self, pop):
        fit_arr=np.zeros(self.pop_size).astype(int)
        for k in range(self.pop_size):
            threat_count=0
            for i in range(self.q_num):
                for j in range(self.q_num):
                    if i != j:
                        if abs(j - i) == abs(pop[k][j] - pop[k][i]) or pop[k][j] == pop[k][i]:
                            threat_count += 1
            fit_arr[k]=(threat_count/2)
        return fit_arr
    
    #Now we get define our crossover function
    def Crossover(self, x, y):
        random.seed(a=None)
        pivot = random.randint(0, self.q_num - 1)
        t = np.zeros(8).astype(int)
        t = np.concatenate((x[0:pivot],y[pivot:self.q_num]))
        return t

    #Mutates all the population
    def Mutate(self, pop):
        random.seed(a=None)
        fit_arr=np.zeros(self.pop_size).astype(int)
        for k in range(self.pop_size):
            if(random.random() < self.m_ch):
                mu_count = random.randint(0, int((self.q_num-1)/2))
                t=[]
                for i in range(mu_count):
                    pos = random.randint(0, self.q_num-1)
                    if pos not in t:
                        t.append(pos)
                        pop[k][pos] = random.randint(0, self.q_num-1)
        return pop
    
    #we just wanna calculate the chance of surviving and return a list of failed solutions for the next round
    #I tried the chance but too many boards would be eliminated in each round so I've used chance*chance
    def RandomSelection(self, pop, max_fitness, fit_arr):
        x=[]
        random.seed(a=None)
        for i in range(self.pop_size):
            chance=fit_arr[i]/max_fitness
            if(random.random() < chance*chance):
                x.append(i)
        return x
    
    #display the board
    def BoardDisplay(self, x):
        for i in range(self.q_num):
            for j in range(self.q_num):
                if x[j]==i:
                    print("|", end="Q")
                else:
                    print("|", end="_")
            print("|")
                
                


In [148]:
s_t=time.time()
t = PogChampQueen(population_size, number_of_queens, mutation_chance)
pop = t.InitPop()
max_fitness= (number_of_queens - 1) * number_of_queens / 2
print(pop)
while True:
    k = t.Fitness(pop)
    print(k)
    if 0 in k:
        ind = k.tolist().index(0)
        print("we got this")
        break
    x = t.RandomSelection(pop, max_fitness, k)
    print("x is:",x)
    f1=0
    f2=0
    for i in k:
        while f1 == f2 or f1 in k or f2 in k:   #just to make sure we don't crossover the nodes that have been eliminated
            f1= random.randint(0, population_size-1)
            f2= random.randint(0, population_size-1)
        if i < population_size:                  
            pop[i]=t.Crossover(pop[f1],pop[f2])
    t.Mutate(pop)
    x.clear
e_t=time.time()
t.BoardDisplay(pop[ind])
print("run_time is:", e_t- s_t)


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: This function is deprecated. Please call randint(0, 5 + 1) instead
  # Remove the CWD from sys.path while we load stuff.


[[5 2 3 5 1 5]
 [2 4 1 0 0 3]
 [5 3 2 2 2 0]
 [5 4 4 0 4 5]
 [5 0 3 4 3 2]
 [4 1 5 0 3 2]
 [0 1 1 1 0 4]
 [1 0 0 2 2 0]
 [1 5 1 0 3 0]
 [3 4 1 3 5 5]
 [2 4 0 3 2 1]
 [5 3 3 4 2 0]
 [0 3 0 3 1 5]
 [1 2 1 4 4 2]
 [4 2 4 1 3 3]
 [3 3 5 1 3 0]
 [4 0 3 3 5 4]
 [1 5 2 2 5 0]
 [3 1 5 2 4 2]
 [2 4 2 5 5 1]]
[7 2 7 6 7 4 7 8 4 5 6 5 5 8 4 6 5 4 4 3]
x is: [6, 7]
[ 7  2  9  6  9  9 10  6  4  5  6  5  5  8  4  6  5  6  4  3]
x is: []
[ 7  2  8  4  4  4  4  4  4  4  8  5  5  8 10  6  5  6  4  3]
x is: [2, 6, 11, 13, 14, 15]
[ 4  2  3  3  3  3  3  2  3  4  3  5  5  8 10  6  5  6  4  3]
x is: [11, 14]
[ 4  2  6 10 10  6  6  2  6  4 10  5  5  8 10  6  5  6  4  3]
x is: [3, 14]
[ 4  2  3  2  3  3  3  1  3  4  2  5  5  8 10  6  5  6  4  3]
x is: [5, 11, 13, 14]
[ 4  3  3  2  3  3  2  1  2  4  4  7  5  8 10  5  5  6  4  3]
x is: [5, 11, 13, 18]
[ 4  4  7  7  5  7  9  5  4  4  5  7  5  8 10  7  5  6  4  3]
x is: [1]
[ 4  4  7  5  4  4  5  5  5  8  4  7  5  8 10  7  5  6  3  3]
x is: [6, 9]
[ 4  4  7  6 1

[5 5 7 5 7 8 5 8 5 3 3 7 6 5 8 6 3 5 4 6]
x is: [4, 14, 15, 19]
[5 5 7 4 4 4 9 7 5 3 3 7 6 5 8 6 3 4 4 6]
x is: [0, 1, 5, 6, 8, 19]
[5 5 7 7 5 5 5 7 5 8 3 7 6 5 8 6 3 4 4 6]
x is: [3, 8, 9, 11, 14]
[ 5  5  7  4  5  5  3  5  5 10  3  7  6  5  8  6  3  4  9  6]
x is: [7, 9, 13]
[5 5 7 4 4 5 6 4 5 5 5 7 6 5 8 6 3 4 9 6]
x is: [7, 9, 18, 19]
[5 5 7 5 5 4 6 7 5 7 5 7 6 5 8 6 3 4 9 6]
x is: [3, 8, 18]
[ 5  5  7  9 10  6  7  9  7  7  5  7  6  5  8  6  3  4  9  6]
x is: [3, 8, 11, 19]
[5 5 7 6 5 5 6 5 6 6 5 7 6 5 8 6 7 4 9 6]
x is: [1, 9, 11, 15]
[5 3 7 7 5 5 3 5 5 3 5 7 6 7 8 6 7 4 9 6]
x is: [11, 12, 14, 16, 18]
[5 3 7 7 9 9 3 9 6 4 8 7 6 7 8 6 7 4 9 6]
x is: [13, 14, 19]
[5 3 7 5 5 6 8 8 7 8 8 7 6 7 8 6 7 4 9 6]
x is: [3, 7, 10, 13, 16]
[5 3 7 7 5 5 8 6 8 9 8 7 6 7 8 6 7 4 9 6]
x is: [12, 14]
[5 3 7 7 8 7 8 8 8 7 8 7 6 7 8 6 7 4 9 6]
x is: [2, 9, 11, 12, 16]
[5 3 7 7 7 5 8 5 7 8 8 7 6 7 8 6 7 4 9 6]
x is: [18]
[5 2 7 7 7 6 6 6 3 7 8 7 6 4 8 6 7 4 9 6]
x is: [2, 6, 11]
[5 2 4 4 4 7 2 2 4 4 8